env:
  node: true
  browser: true
  es2021: true
extends:
  - google
  - eslint:recommended
  - 'plugin:solid/typescript'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - solid
  - prettier
rules: {"prettier/prettier": "error"}
